{% set name = "ninja_syntax" %}
{% set version = "1.7.2" %}
{% set sha256 = "342dc97b9e88a6495bae22953ee6063f91d2f03db6f727b62ba5c3092a18ef1f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - ninja_syntax

about:
  home: https://pypi.python.org/pypi/ninja_syntax/1.6.0
  license: Apache-2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'  # From https://github.com/ninja-build/ninja
  summary: 'Python module for generating .ninja files.'

extra:
  recipe-maintainers:
    - dfroger
