{% set name = "ninja_syntax" %}
{% set version = "1.6.0" %}
{% set sha256 = "33c203b4ee39a638c9af757ed1c4257e05abf1fae0615305d103020f36c804c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - ninja_syntax

about:
  home: https://pypi.python.org/pypi/ninja_syntax/1.6.0
  license: Apache-2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'  # From https://github.com/ninja-build/ninja
  summary: 'Python module for generating .ninja files.'

extra:
  recipe-maintainers:
    - dfroger
