appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: SLXXdO5wNf9yO3B2fvvU3ibHRJlcREguhjfE6qOKRViPavR3leszFxkE4l+3Xdw/cHYg/Kv6ubziOm94Ln7QaylljHm/ekNFZfL/sLacFhqsaNwm2S7wmK42BDI7DD5tyTfwCE+J7I6D3qZM1Txi5D8ahEGPiWSVAHWXyiFDDriGpg+SY+77adyQS/XSkNRPxglYmienicGGgltfLOyehp4oW8p8+MzqLiGwnnK6D9BSE/PGhbmPX/3RNxvl8pbnw5M2q6rwbXTaSk+kkmi6crhSrRT3HilWzuYejQJi2GbkC+OqkdTuqaHLcl/3hFBaazbVuhcQIBvqa16Er/8nUDSHOSoZeD3qvmEFmddWBIln9A86gPtUFPW8sDtlkaBTa78q9vqG9PmcWDxraE2VDrVpPZWOW/Rzidec/MUpcknNM51uZajTZarDHd9SpxPQoEdqBa9AIU2zSIrQfFuGmGm0w7NfrzZCAQmNbF3e9+KdB5GS3SxTwm5dIMtzp/qVCwqeGChyBvlhdb0csqNi++fTBlZd4tN1lQtZmUJK8D3dPPvoO4OtmchaGfMO26XbLPLEbLkh+ukaYdAFVURyNQlphTwN0TY2+0b4V3qBiD+qFH3PcldgZUcOdbxJxgf/LZBfTMs5KoiBUNrVOtZZhTE62+eVzbccYfOeTAXstho=}
conda_forge_output_validation: true
