travis:
  secure:
    BINSTAR_TOKEN: uAWzHSJGsJZ3WmyofxTm3d3OZTuD1N0Fvcxd1c8ANYND+YWzvHQvE3zPkQiSd663I813TRzeAWr6PZbpMAAj9br9IJVr1AC4O1fSx74x74WZtHoL3Q8OO4/8sdpdXtmkhHjMH48zOWHucC0ptP0D61dlI7NyPrJOMrmje6Cn/V3NXOdLwVariTfKOZCaba9jejKVc+5usp6jHxY3mh6GsSw1fxYbNO7sFc3Zid7P66OzuA7KTtICxKiwnPtRAdpjpGQxxSOGrMOB8/XyAZNDQfu9SyGelEaphOgbWpOZwawfKlMu8OgLqaPiuOPsFcNoLCaKKaffiDugMdXFOwvoGu37RmseVM/0MBe5CLIA3+WSI/7yCiVx7XYXsTMxeyfTIvls0kv+YNsLH4VUgsHqdj/ZFqRsUrw+gF38k2cQJOFmU4g0xyOZxg9SruJI+YOc1BmzGin32zs0muyY3++CnfPKOjcSlE0CKs/i0X7TnWV0gZv6EYx2R5rBi054bVR3/0vvvJAMyrf+o3UvnED/jgpk4JBPhd7Xb26OvCjbI+qUzqf3WFpw+3scJJtIIrXivvEGzBoMwvoIJK1gZldXLWuyGsTf1Ui4sLZHyfh+QTfooQ4c6ydRJ42/ItdUD7vvYOHd+q5J08QAYoSgPFqMhPo0Ct2M5I/lJOdxG2nOtWI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
